# Generated by Django 5.1.4 on 2024-12-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': "AI's Diagnosis", 'verbose_name_plural': "AI's Diagnoses"},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(editable=False, verbose_name='AI Explanation'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease_category',
            field=models.CharField(max_length=250, verbose_name='Disease Category'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='symptoms',
            field=models.CharField(max_length=250, verbose_name='Symptoms'),
        ),
    ]
