# Generated by Django 5.1.4 on 2024-12-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Назначенное Время')),
                ('status', models.CharField(default='ожидание', max_length=10, verbose_name='Статус Заявки')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявление на прием',
                'verbose_name_plural': 'Заявления на прием',
            },
        ),
    ]
