# Generated by Django 5.1.4 on 2024-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='spezialisation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания'),
        ),
    ]
